name: Sync fork

on:
  schedule:
    - cron: "*/2 * * * *" 

  workflow_dispatch: 

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync the tags

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: hellozee
        token: ${{ secrets.PAT }}

    - name: Sync the tags
      run: |
        bash ./fetch_all_tags.sh