name: Sync fork

on:
  schedule:
    - cron: "*/2 * * * *" 

  workflow_dispatch: 

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync the tags

    steps:
    - name: Sync the tags
      run: |
        bash ./fetch_all_tags.sh